begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions,pg_catalog;
select plan(29);
insert into auth.users(id,email) values
('93900000-0000-4000-8000-000000000001','teacher@followup.test'),
('93900000-0000-4000-8000-000000000002','learner@followup.test'),
('93900000-0000-4000-8000-000000000003','other@followup.test');
insert into public.user_roles(user_id,role) values('93900000-0000-4000-8000-000000000001','teacher');
insert into public.classes(id,owner_user_id,name,join_code) values(939001,'93900000-0000-4000-8000-000000000001','Follow-up Class','9390AAAABBBBCCCC');
alter sequence public.class_announcements_id_seq restart with 1;
set local role postgres;
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000001';
select is(public.publish_class_announcement(939001,'Friday test','Test is Friday.'),1::bigint,'announcement starts at revision one');
select is((select revision from public.class_announcements where id=1),1,'initial revision is one');
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000002';
select lives_ok($$insert into public.class_enrollments(class_id,learner_user_id) values(939001,auth.uid())$$,'late enrollment succeeds');
select is((select count(*)::integer from public.learner_notifications where learner_user_id=auth.uid() and notification_type='new_announcement'),1,'late enrollment receives one announcement notification');
select is((select (public.get_class_announcements(939001)->0->>'readRevision')::integer),null::integer,'new learner has no fabricated read revision');
select lives_ok($$select public.mark_class_announcement_read(1)$$,'learner reads revision one');
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000001';
select is(public.edit_class_announcement(1,'Monday test','Test moved to Monday.'),2,'meaningful edit advances revision');
select is((select count(*)::integer from public.class_announcements),1,'edit preserves announcement identity');
select is((select published_at from public.class_announcements where id=1),(select created_at from public.class_announcements where id=1),'edit preserves original publication time');
select is((select read_revision from public.class_announcement_reads where announcement_id=1),1,'old read revision remains stored');
select is((select x."readCount"::integer from jsonb_to_recordset(public.get_class_announcements(939001)) as x("readCount" integer)),0,'current revision read count excludes stale read');
select is((select count(*)::integer from public.learner_notifications where notification_type='announcement_updated'),1,'edit emits updated notification');
select is(public.edit_class_announcement(1,'Monday test','Test moved to Monday.'),2,'no-op edit does not advance revision');
select is((select count(*)::integer from public.learner_notifications where notification_type='announcement_updated'),1,'same revision update is deduplicated');
select lives_ok($$select public.edit_class_announcement(1,'Tuesday test','Test moved to Tuesday.')$$,'second meaningful edit succeeds');
select is((select count(*)::integer from public.learner_notifications where notification_type='announcement_updated'),2,'next revision has distinct notification event');
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000002';
select is((select (public.get_class_announcements(939001)->0->>'readRevision')::integer),1,'edited announcement is unread at latest revision');
select lives_ok($$select public.mark_all_class_announcements_read(939001)$$,'mark all reads current revision');
select is((select read_revision from public.class_announcement_reads where announcement_id=1),3,'mark all stores current revision');
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000001';
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000003';
select lives_ok($$select public.withdraw_class_announcement(1)$$,'unauthorized Teacher cannot withdraw announcement');
select ok((select withdrawn_at is null from public.class_announcements where id=1),'unauthorized withdrawal leaves announcement active');
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000001';
select lives_ok($$select public.withdraw_class_announcement(1)$$,'teacher can remove announcement');
select is(jsonb_array_length(public.get_class_announcements(939001)),0,'removed announcement is absent from normal teacher view');
set local request.jwt.claim.sub='93900000-0000-4000-8000-000000000002';
select is(jsonb_array_length(public.get_my_notifications(100)),0,'withdrawn notifications are absent from learner inbox');
select ok((select exists(select 1 from public.learner_notifications where announcement_id=1 and body='Test moved to Tuesday.')),'internal notification history remains retained for audit');
select is((select count(*)::integer from public.learner_notifications where announcement_id=1),3,'withdrawal preserves notification event history');
select lives_ok($$update public.class_enrollments set status='inactive' where class_id=939001 and learner_user_id=auth.uid()$$,'learner can become inactive');
select lives_ok($$update public.class_enrollments set status='active' where class_id=939001 and learner_user_id=auth.uid()$$,'learner can reactivate');
select is((select count(*)::integer from public.learner_notifications where announcement_id=1),3,'reactivation does not revive withdrawn notification events');
select * from finish();
rollback;
