export const routeModuleLoaders = {
  dashboard: () => import("../../features/dashboard/DashboardPage"),
  courses: () => import("../../features/courses/CoursesPage"),
  sharedCourse: () => import("../../features/courses/SharedCoursePage"),
  units: () => import("../../features/units/UnitsPage"),
  lessons: () => import("../../features/lessons/LessonsPage"),
  lesson: () => import("../../features/lesson/LessonPage"),
  login: () => import("../../features/auth/LoginPage"),
  adminRoute: () => import("../../features/admin/routing/AdminRoute"),
  adminLayout: () => import("../../features/admin/layouts/AdminLayout"),
  adminDashboard: () => import("../../features/admin/dashboard/AdminDashboardPage"),
  adminCourses: () => import("../../features/admin/courses/AdminCoursesPage"),
  courseWorkspace: () => import("../../features/admin/units/AdminCourseUnitsPage"),
  unitLessons: () => import("../../features/admin/lessons/AdminUnitLessonsPage"),
  lessonStudio: () => import("../../features/admin/lesson-studio/pages/LessonStudioPage"),
  classes: () => import("../../features/admin/classes/AdminClassesPage"),
  createClass: () => import("../../features/admin/classes/CreateClassForm").then((module) => ({ default: module.CreateClassForm })),
  classWorkspace: () => import("../../features/admin/classes/ClassWorkspaceLayout").then((module) => ({ default: module.ClassWorkspaceLayout })),
  learnerClasses: () => import("../../features/classes/LearnerClassesPage"),
  releaseCourse: () => import("../../features/releases/ReleaseCoursePage"),
  releaseLesson: () => import("../../features/releases/ReleaseLessonPage"),
  previewCourse: () => import("../../features/admin/preview/StudentPreviewCoursePage"),
  previewLesson: () => import("../../features/admin/preview/StudentPreviewLessonPage"),
  mediaLibrary: () => import("../../features/admin/media/AdminMediaLibraryPage"),
} as const;
