import { Link, useSearchParams } from "react-router-dom";
import { previewExitPath } from "./previewNavigation";
import { previewViewportModes, type PreviewViewportMode } from "./previewViewport";

export function StudentPreviewToolbar({ returnPath, draft = false, source = draft ? "draft" : "published", viewportMode, onViewportModeChange }: { returnPath: string; draft?: boolean; source?: "draft" | "published" | "local"; viewportMode?: PreviewViewportMode; onViewportModeChange?: (mode: PreviewViewportMode) => void }) {
  const [searchParams] = useSearchParams();
  const exitPath = previewExitPath(searchParams.get("returnTo"), searchParams.get("activity"), returnPath);
  const label = source === "draft" ? "Draft Preview" : source === "local" ? "Local Content Preview" : "Published Preview";
  const detail = source === "local" ? "This preview uses local learner content because no saved remote version is available." : "You are viewing this content as a student. Preview responses are not saved.";
  return <div className="sticky top-0 z-40 border-b border-blue-200 bg-blue-50 px-4 py-3 text-blue-950 shadow-sm"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between"><div className="min-w-0"><span className="mr-2 inline-flex rounded-full bg-blue-700 px-2.5 py-1 text-xs font-bold text-white">Student Preview</span><span className="text-sm font-semibold">{label}</span><span className="mt-1 block text-xs leading-5 text-blue-800 sm:ml-2 sm:mt-0 sm:inline">{detail}</span></div><div className="flex w-full flex-wrap items-center gap-2 sm:w-auto">{viewportMode && onViewportModeChange && <div role="group" aria-label="Preview size" className="flex flex-1 rounded-lg border border-blue-300 bg-white p-1 sm:flex-none">{previewViewportModes.map((mode) => <button key={mode} type="button" aria-label={`${mode[0].toUpperCase()}${mode.slice(1)} preview`} aria-pressed={viewportMode === mode} onClick={() => onViewportModeChange(mode)} className={`min-h-11 flex-1 rounded-md px-3 text-xs font-semibold capitalize sm:flex-none ${viewportMode === mode ? "bg-blue-700 text-white" : "text-blue-800 hover:bg-blue-50"}`}>{mode}</button>)}</div>}<Link to={exitPath} className="admin-focus inline-flex min-h-11 flex-1 items-center justify-center rounded-lg border border-blue-300 bg-white px-3 py-1.5 text-sm font-semibold text-blue-800 hover:bg-blue-100 sm:flex-none">Exit Preview</Link></div></div></div>;
}
