import { Link, useSearchParams } from "react-router-dom";
import { previewExitPath } from "./previewNavigation";
import { previewViewportModes, type PreviewViewportMode } from "./previewViewport";

export function StudentPreviewToolbar({ returnPath, draft = false, source = draft ? "draft" : "published", viewportMode, onViewportModeChange }: { returnPath: string; draft?: boolean; source?: "draft" | "published" | "local"; viewportMode?: PreviewViewportMode; onViewportModeChange?: (mode: PreviewViewportMode) => void }) {
  const [searchParams] = useSearchParams();
  const exitPath = previewExitPath(searchParams.get("returnTo"), searchParams.get("activity"), returnPath);
  const label = source === "draft" ? "Draft Preview" : source === "local" ? "Local Content Preview" : "Published Preview";
  const detail = source === "local" ? "This preview uses local learner content because no saved remote version is available." : "You are viewing this content as a student. Preview responses are not saved.";
  return <div className="sticky top-0 z-40 border-b border-blue-200 bg-blue-50 px-4 py-3 text-blue-950 shadow-sm"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><div><span className="mr-2 inline-flex rounded-full bg-blue-700 px-2.5 py-1 text-xs font-bold text-white">Student Preview</span><span className="text-sm font-semibold">{label}</span><span className="ml-2 text-xs text-blue-800">{detail}</span></div><div className="flex flex-wrap items-center gap-3">{viewportMode && onViewportModeChange && <div role="group" aria-label="Preview size" className="flex rounded-lg border border-blue-300 bg-white p-1">{previewViewportModes.map((mode) => <button key={mode} type="button" aria-label={`${mode[0].toUpperCase()}${mode.slice(1)} preview`} aria-pressed={viewportMode === mode} onClick={() => onViewportModeChange(mode)} className={`min-h-9 rounded-md px-3 text-xs font-semibold capitalize ${viewportMode === mode ? "bg-blue-700 text-white" : "text-blue-800"}`}>{mode}</button>)}</div>}<Link to={exitPath} className="admin-focus inline-flex min-h-9 items-center rounded-lg border border-blue-300 bg-white px-3 py-1.5 text-sm font-semibold text-blue-800">Exit Preview</Link></div></div></div>;
}
