begin;

create table public.course_releases (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete restrict,
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  release_number integer not null check (release_number > 0),
  course_slug text not null,
  course_title text not null,
  course_description text not null,
  course_level text not null,
  course_emoji text not null,
  content_fingerprint text not null check (content_fingerprint ~ '^[a-f0-9]{64}$'),
  released_at timestamptz not null default pg_catalog.now(),
  unique(course_id, release_number), unique(course_id, content_fingerprint)
);
create table public.course_release_units (
  id bigint generated by default as identity primary key,
  course_release_id bigint not null references public.course_releases(id) on delete restrict,
  source_unit_id bigint not null references public.units(id) on delete restrict,
  position integer not null check(position >= 0), title text not null, description text not null,
  unique(course_release_id, source_unit_id), unique(course_release_id, position)
);
create table public.course_release_lessons (
  id bigint generated by default as identity primary key,
  course_release_unit_id bigint not null references public.course_release_units(id) on delete restrict,
  source_lesson_id bigint not null references public.lessons(id) on delete restrict,
  lesson_version_id bigint not null references public.lesson_versions(id) on delete restrict,
  position integer not null check(position >= 0), title text not null, description text not null,
  unique(course_release_unit_id, source_lesson_id), unique(course_release_unit_id, position)
);

-- Temporary production-safe entitlement seam. Class assignments will become an
-- additional authorization source; this table is not writable by browser roles.
create table public.course_release_learner_entitlements (
  course_release_id bigint not null references public.course_releases(id) on delete restrict,
  learner_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default pg_catalog.now(),
  primary key(course_release_id, learner_id)
);

create table public.learner_release_lesson_progress (
  learner_id uuid not null references auth.users(id) on delete cascade,
  course_release_lesson_id bigint not null references public.course_release_lessons(id) on delete restrict,
  started_at timestamptz not null default pg_catalog.now(), completed_at timestamptz,
  last_activity_id bigint references public.lesson_activities(id) on delete set null,
  last_accessed_at timestamptz not null default pg_catalog.now(),
  primary key(learner_id, course_release_lesson_id),
  check(completed_at is null or completed_at >= started_at)
);
create table public.learner_release_activity_progress (
  learner_id uuid not null references auth.users(id) on delete cascade,
  course_release_lesson_id bigint not null references public.course_release_lessons(id) on delete restrict,
  activity_id bigint not null references public.lesson_activities(id) on delete restrict,
  completed_at timestamptz not null default pg_catalog.now(),
  primary key(learner_id, course_release_lesson_id, activity_id)
);

create or replace function public.reject_immutable_release_mutation() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'Course Release manifests are immutable'; end; $$;
create trigger course_releases_immutable before update or delete on public.course_releases for each row execute function public.reject_immutable_release_mutation();
create trigger course_release_units_immutable before update or delete on public.course_release_units for each row execute function public.reject_immutable_release_mutation();
create trigger course_release_lessons_immutable before update or delete on public.course_release_lessons for each row execute function public.reject_immutable_release_mutation();

create or replace function public.create_course_release_from_published(requested_course_id bigint) returns bigint
language plpgsql security definer set search_path='' as $$
declare manifest jsonb; fingerprint text; existing_id bigint; release_id bigint; unit_row record; release_unit_id bigint;
begin
  select jsonb_build_object('course',jsonb_build_object('id',c.id,'slug',c.slug,'title',c.title,'description',c.description,'level',c.level,'emoji',c.emoji),
    'units',coalesce((select jsonb_agg(jsonb_build_object('sourceUnitId',u.id,'position',u.position,'title',u.title,'description',u.description,
      'lessons',coalesce((select jsonb_agg(jsonb_build_object('sourceLessonId',l.id,'lessonVersionId',l.current_published_version_id,'position',l.position,'title',l.title,'description',l.description) order by l.position,l.id)
        from public.lessons l join public.lesson_versions v on v.id=l.current_published_version_id and v.lesson_id=l.id and v.status='published'
        where l.unit_id=u.id and l.status='published'),'[]'::jsonb)) order by u.position,u.id)
      from public.units u where u.course_id=c.id and u.status='published'),'[]'::jsonb)) into manifest
  from public.courses c where c.id=requested_course_id and c.status='published';
  if manifest is null or jsonb_array_length(manifest->'units')=0 or exists(
    select 1 from jsonb_array_elements(manifest->'units') u where jsonb_array_length(u->'lessons')=0
  ) then raise exception 'A complete published Course is required for release creation'; end if;
  fingerprint:=encode(extensions.digest(convert_to(manifest::text,'UTF8'),'sha256'),'hex');
  select id into existing_id from public.course_releases where course_id=requested_course_id and content_fingerprint=fingerprint;
  if existing_id is not null then return existing_id; end if;
  insert into public.course_releases(course_id,owner_user_id,release_number,course_slug,course_title,course_description,course_level,course_emoji,content_fingerprint)
  select c.id,c.owner_user_id,coalesce((select max(r.release_number)+1 from public.course_releases r where r.course_id=c.id),1),c.slug,c.title,c.description,c.level,c.emoji,fingerprint from public.courses c where c.id=requested_course_id returning id into release_id;
  for unit_row in select u.* from public.units u where u.course_id=requested_course_id and u.status='published' order by u.position,u.id loop
    insert into public.course_release_units(course_release_id,source_unit_id,position,title,description) values(release_id,unit_row.id,unit_row.position,unit_row.title,unit_row.description) returning id into release_unit_id;
    insert into public.course_release_lessons(course_release_unit_id,source_lesson_id,lesson_version_id,position,title,description)
    select release_unit_id,l.id,l.current_published_version_id,l.position,l.title,l.description from public.lessons l join public.lesson_versions v on v.id=l.current_published_version_id and v.lesson_id=l.id and v.status='published' where l.unit_id=unit_row.id and l.status='published' order by l.position,l.id;
  end loop;
  return release_id;
exception when unique_violation then select id into existing_id from public.course_releases where course_id=requested_course_id and content_fingerprint=fingerprint; return existing_id;
end; $$;

create or replace function public.capture_course_release_after_publication() returns trigger language plpgsql security definer set search_path='' as $$
begin
  -- Legacy/import/test SQL can construct published rows incrementally. Only a
  -- complete hierarchy is eligible; publish_course reaches this state before
  -- its final Course update, so normal publication still captures atomically.
  if new.status='published' and exists(select 1 from public.units u where u.course_id=new.id and u.status='published')
    and not exists(select 1 from public.units u where u.course_id=new.id and u.status='published' and not exists(select 1 from public.lessons l join public.lesson_versions v on v.id=l.current_published_version_id and v.lesson_id=l.id and v.status='published' where l.unit_id=u.id and l.status='published'))
  then perform public.create_course_release_from_published(new.id); end if;
  return new;
end; $$;
create constraint trigger capture_course_release_after_publication after update on public.courses deferrable initially deferred for each row when(new.status='published') execute function public.capture_course_release_after_publication();

create or replace function public.can_access_course_release(requested_release_id bigint) returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.course_releases r where r.id=requested_release_id and (r.owner_user_id=auth.uid() or public.is_platform_admin()))
    or (public.is_learner_identity() and exists(select 1 from public.course_release_learner_entitlements e where e.course_release_id=requested_release_id and e.learner_id=auth.uid()));
$$;

create or replace function public.get_course_release_manifest(requested_release_id bigint) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin if not public.can_access_course_release(requested_release_id) then raise exception 'Course Release is unavailable'; end if;
return (select jsonb_build_object('id',r.id,'courseId',r.course_id,'releaseNumber',r.release_number,'title',r.course_title,'description',r.course_description,'level',r.course_level,'emoji',r.course_emoji,'releasedAt',r.released_at,'fingerprint',r.content_fingerprint,
'units',coalesce((select jsonb_agg(jsonb_build_object('id',u.id,'sourceUnitId',u.source_unit_id,'position',u.position,'title',u.title,'description',u.description,'lessons',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'sourceLessonId',l.source_lesson_id,'lessonVersionId',l.lesson_version_id,'position',l.position,'title',l.title,'description',l.description) order by l.position,l.id) from public.course_release_lessons l where l.course_release_unit_id=u.id),'[]'::jsonb)) order by u.position,u.id) from public.course_release_units u where u.course_release_id=r.id),'[]'::jsonb)) from public.course_releases r where r.id=requested_release_id); end; $$;

create or replace function public.get_course_release_lesson(requested_release_lesson_id bigint,requested_schema_version integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare payload jsonb; release_id bigint; learner uuid:=auth.uid(); already_completed boolean;
begin select u.course_release_id into release_id from public.course_release_lessons l join public.course_release_units u on u.id=l.course_release_unit_id where l.id=requested_release_lesson_id;
if release_id is null then raise exception using errcode='PLR02',message='Release Lesson does not exist'; end if;
if not public.can_access_course_release(release_id) then raise exception using errcode='PLR01',message='Course Release is unavailable'; end if;
if requested_schema_version<>1 then raise exception 'Unsupported schema version'; end if;
if public.is_learner_identity() then
  select exists(select 1 from public.learner_release_lesson_progress p where p.learner_id=learner and p.course_release_lesson_id=requested_release_lesson_id and p.completed_at is not null) into already_completed;
  if not already_completed and not public.release_lesson_is_eligible(learner,requested_release_lesson_id) then
    return jsonb_build_object('schemaVersion',1,'courseReleaseId',release_id,'releaseLessonId',requested_release_lesson_id,'locked',true,'error',jsonb_build_object('code','release_lesson_locked','message','Complete the previous lesson first.'),'lesson',null);
  end if;
end if;
select jsonb_build_object('schemaVersion',1,'courseReleaseId',u.course_release_id,'releaseLessonId',l.id,'lessonRevision',v.id::text||':'||v.version_number::text,'lesson',jsonb_build_object('id',l.source_lesson_id::text,'unitId',u.source_unit_id::text,'title',l.title,'description',l.description,'currentVersionId',v.id::text,'versionNumber',v.version_number,'publishedAt',v.published_at,'activities',coalesce((select jsonb_agg(public.learner_pronunciation_activity_v2(public.learner_published_activity_projection(a.id)) order by a.position,a.id) from public.lesson_activities a where a.lesson_version_id=v.id),'[]'::jsonb))) into payload
from public.course_release_lessons l join public.course_release_units u on u.id=l.course_release_unit_id join public.lesson_versions v on v.id=l.lesson_version_id and v.lesson_id=l.source_lesson_id where l.id=requested_release_lesson_id and v.status in ('published','archived'); return payload; end; $$;

create or replace function public.release_lesson_is_eligible(requested_learner uuid,requested_release_lesson bigint) returns boolean language sql stable security definer set search_path='' as $$
select exists(select 1 from public.course_release_lessons target join public.course_release_units tu on tu.id=target.course_release_unit_id where target.id=requested_release_lesson and not exists(
 select 1 from public.course_release_lessons prior join public.course_release_units pu on pu.id=prior.course_release_unit_id
 where pu.course_release_id=tu.course_release_id
   and (pu.position,prior.position,prior.id)<(tu.position,target.position,target.id)
   and not exists(select 1 from public.learner_release_lesson_progress p where p.learner_id=requested_learner and p.course_release_lesson_id=prior.id and p.completed_at is not null))); $$;

create or replace function public.record_release_activity_completion(requested_release_lesson_id bigint,requested_activity_id bigint) returns jsonb language plpgsql security definer set search_path='' as $$
declare learner uuid:=auth.uid(); release_id bigint; version_id bigint; lesson_complete boolean; completed timestamptz;
begin if not public.is_learner_identity() then raise exception using errcode='PLR04',message='Learner authentication is required'; end if;
select u.course_release_id,l.lesson_version_id into release_id,version_id from public.course_release_lessons l join public.course_release_units u on u.id=l.course_release_unit_id where l.id=requested_release_lesson_id;
if release_id is null then raise exception using errcode='PLR02',message='Release Lesson does not exist'; end if;
if not public.can_access_course_release(release_id) then raise exception using errcode='PLR01',message='Course Release is unavailable'; end if;
if not exists(select 1 from public.lesson_activities where id=requested_activity_id and lesson_version_id=version_id) then raise exception using errcode='PLR05',message='Activity is not part of the pinned Lesson version'; end if;
if not public.release_lesson_is_eligible(learner,requested_release_lesson_id) and not exists(select 1 from public.learner_release_lesson_progress p where p.learner_id=learner and p.course_release_lesson_id=requested_release_lesson_id and p.completed_at is not null) then raise exception using errcode='PLR03',message='Complete the previous Release content first'; end if;
insert into public.learner_release_activity_progress values(learner,requested_release_lesson_id,requested_activity_id,pg_catalog.now()) on conflict(learner_id,course_release_lesson_id,activity_id) do update set completed_at=public.learner_release_activity_progress.completed_at returning completed_at into completed;
select not exists(select 1 from public.lesson_activities a where a.lesson_version_id=version_id and not exists(select 1 from public.learner_release_activity_progress p where p.learner_id=learner and p.course_release_lesson_id=requested_release_lesson_id and p.activity_id=a.id)) into lesson_complete;
insert into public.learner_release_lesson_progress(learner_id,course_release_lesson_id,completed_at,last_activity_id) values(learner,requested_release_lesson_id,case when lesson_complete then completed end,requested_activity_id) on conflict(learner_id,course_release_lesson_id) do update set completed_at=coalesce(public.learner_release_lesson_progress.completed_at,excluded.completed_at),last_activity_id=excluded.last_activity_id,last_accessed_at=pg_catalog.now();
return jsonb_build_object('releaseLessonId',requested_release_lesson_id,'activityId',requested_activity_id,'lessonComplete',lesson_complete,'completedAt',completed); end; $$;

create or replace function public.get_my_course_release_progress(requested_release_id bigint) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin if not public.is_learner_identity() or not public.can_access_course_release(requested_release_id) then raise exception 'Course Release is unavailable'; end if;
return jsonb_build_object('lessons',coalesce((select jsonb_agg(jsonb_build_object('releaseLessonId',l.id,'lessonVersionId',l.lesson_version_id,'startedAt',p.started_at,'completedAt',p.completed_at,'lastAccessedAt',p.last_accessed_at,'eligible',public.release_lesson_is_eligible(auth.uid(),l.id),'state',case when p.completed_at is not null then 'completed' when public.release_lesson_is_eligible(auth.uid(),l.id) then 'available' else 'locked' end) order by u.position,l.position) from public.course_release_lessons l join public.course_release_units u on u.id=l.course_release_unit_id left join public.learner_release_lesson_progress p on p.course_release_lesson_id=l.id and p.learner_id=auth.uid() where u.course_release_id=requested_release_id),'[]'::jsonb),'activities',coalesce((select jsonb_agg(jsonb_build_object('releaseLessonId',p.course_release_lesson_id,'activityId',p.activity_id,'completedAt',p.completed_at)) from public.learner_release_activity_progress p join public.course_release_lessons l on l.id=p.course_release_lesson_id join public.course_release_units u on u.id=l.course_release_unit_id where p.learner_id=auth.uid() and u.course_release_id=requested_release_id),'[]'::jsonb)); end; $$;

alter table public.course_releases enable row level security; alter table public.course_release_units enable row level security; alter table public.course_release_lessons enable row level security; alter table public.course_release_learner_entitlements enable row level security; alter table public.learner_release_lesson_progress enable row level security; alter table public.learner_release_activity_progress enable row level security;
create policy release_progress_own_lesson on public.learner_release_lesson_progress for select to authenticated using(learner_id=auth.uid() or public.is_platform_admin());
create policy release_progress_own_activity on public.learner_release_activity_progress for select to authenticated using(learner_id=auth.uid() or public.is_platform_admin());
grant select on public.learner_release_lesson_progress,public.learner_release_activity_progress to authenticated;
revoke all on public.course_releases,public.course_release_units,public.course_release_lessons,public.course_release_learner_entitlements from anon,authenticated;
revoke all on function public.create_course_release_from_published(bigint),public.can_access_course_release(bigint),public.release_lesson_is_eligible(uuid,bigint) from public,anon,authenticated;
revoke all on function public.get_course_release_manifest(bigint),public.get_course_release_lesson(bigint,integer),public.record_release_activity_completion(bigint,bigint),public.get_my_course_release_progress(bigint) from public,anon;
grant execute on function public.get_course_release_manifest(bigint),public.get_course_release_lesson(bigint,integer),public.record_release_activity_completion(bigint,bigint),public.get_my_course_release_progress(bigint) to authenticated;
commit;
