begin;

alter table public.learner_notifications
  alter column assignment_id drop not null,
  alter column course_release_id drop not null;
alter table public.learner_notifications drop constraint learner_notifications_notification_type_check;
alter table public.learner_notifications add constraint learner_notifications_notification_type_check
  check (notification_type in ('new_assignment','assignment_available','due_soon','assignment_late','new_announcement','announcement_updated'));
alter table public.learner_notifications add column announcement_id bigint;
create index learner_notifications_announcement_idx on public.learner_notifications(announcement_id) where announcement_id is not null;

create table public.class_announcements (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete restrict,
  author_user_id uuid not null references auth.users(id) on delete restrict,
  title text not null check (length(btrim(title)) between 1 and 160),
  body text not null check (length(btrim(body)) between 1 and 5000),
  revision integer not null default 1 check (revision >= 1),
  published_at timestamptz not null default pg_catalog.now(),
  edited_at timestamptz,
  withdrawn_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now()
);
alter table public.learner_notifications add constraint learner_notifications_announcement_fk foreign key (announcement_id) references public.class_announcements(id) on delete restrict;
create index class_announcements_class_idx on public.class_announcements(class_id,published_at desc);
alter table public.class_announcements enable row level security;
create or replace function public.is_active_class_announcement(requested_announcement_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.class_announcements where id=requested_announcement_id and withdrawn_at is null);
$$;
drop policy if exists learner_notifications_select_own on public.learner_notifications;
create policy learner_notifications_select_own on public.learner_notifications for select to authenticated
  using (learner_user_id=auth.uid() and (announcement_id is null or public.is_active_class_announcement(announcement_id)));

create table public.class_announcement_reads (
  announcement_id bigint not null references public.class_announcements(id) on delete restrict,
  learner_user_id uuid not null references auth.users(id) on delete cascade,
  read_revision integer not null default 1 check (read_revision >= 1),
  read_at timestamptz not null default pg_catalog.now(),
  primary key (announcement_id,learner_user_id)
);
alter table public.class_announcement_reads enable row level security;

create or replace function public.create_class_announcement_notification(requested_announcement_id bigint, requested_learner_id uuid, requested_type text default 'new_announcement', requested_event_key text default null)
returns bigint language plpgsql security definer set search_path='' as $$
declare announcement_row record; notification_id bigint; event_key_value text;
begin
  select ca.*,c.name as class_name into announcement_row from public.class_announcements ca join public.classes c on c.id=ca.class_id where ca.id=requested_announcement_id and ca.withdrawn_at is null;
  if announcement_row.id is null or requested_type not in ('new_announcement','announcement_updated') or not exists(select 1 from public.class_enrollments e where e.class_id=announcement_row.class_id and e.learner_user_id=requested_learner_id and e.status='active') then return null; end if;
  event_key_value:=coalesce(requested_event_key,'announcement:'||announcement_row.id||':'||case when requested_type='new_announcement' then 'new' else 'updated:'||announcement_row.revision::text end);
  insert into public.learner_notifications(learner_user_id,notification_type,class_id,announcement_id,title,body,metadata,event_key)
  values(requested_learner_id,requested_type,announcement_row.class_id,announcement_row.id,case when requested_type='new_announcement' then 'New announcement' else 'Announcement updated' end,announcement_row.body,jsonb_build_object('className',announcement_row.class_name,'announcementTitle',announcement_row.title,'announcementRevision',announcement_row.revision),event_key_value)
  on conflict (learner_user_id,event_key) do nothing returning id into notification_id;
  return notification_id;
end; $$;

create or replace function public.backfill_class_announcement_notifications(requested_class_id bigint, requested_learner_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare a record;
begin
  if not exists(select 1 from public.class_enrollments e join public.classes c on c.id=e.class_id where e.class_id=requested_class_id and e.learner_user_id=requested_learner_id and e.status='active' and c.status='active') then return; end if;
  for a in select id,revision from public.class_announcements where class_id=requested_class_id and withdrawn_at is null and published_at >= pg_catalog.now()-interval '90 days' order by published_at desc limit 20 loop
    perform public.create_class_announcement_notification(a.id,requested_learner_id,'new_announcement','announcement:'||a.id||':new');
    if exists(select 1 from public.class_announcement_reads r where r.announcement_id=a.id and r.learner_user_id=requested_learner_id and r.read_revision<a.revision) then
      perform public.create_class_announcement_notification(a.id,requested_learner_id,'announcement_updated','announcement:'||a.id||':updated:'||a.revision::text);
    end if;
  end loop;
end; $$;

create or replace function public.get_my_notifications(requested_limit integer default 50)
returns jsonb language sql stable security definer set search_path='' as $$
  select coalesce(jsonb_agg(item order by item->>'createdAt' desc), '[]'::jsonb)
  from (select jsonb_build_object('id',n.id,'type',n.notification_type,'classId',n.class_id,'assignmentId',n.assignment_id,'releaseId',n.course_release_id,'announcementId',n.announcement_id,
      'title',case when n.announcement_id is not null and a.withdrawn_at is not null then 'Announcement unavailable' when n.announcement_id is not null then case when n.notification_type='announcement_updated' then 'Announcement updated' else 'New announcement' end else n.title end,
      'body',case when n.announcement_id is not null and a.withdrawn_at is not null then 'This announcement is no longer available.' when n.announcement_id is not null then a.body else n.body end,
      'metadata',case when n.announcement_id is not null and a.withdrawn_at is null then n.metadata || jsonb_build_object('announcementTitle',a.title,'announcementRevision',a.revision) else n.metadata end,
      'createdAt',n.created_at,'readAt',n.read_at) as item
    from public.learner_notifications n left join public.class_announcements a on a.id=n.announcement_id
    where n.learner_user_id=auth.uid() and n.dismissed_at is null
      and (n.announcement_id is null or a.withdrawn_at is null)
      and (n.read_at is null or n.read_at > pg_catalog.now() - interval '90 days')
    order by n.created_at desc limit least(greatest(coalesce(requested_limit,50),1),100)) q;
$$;

create or replace function public.publish_class_announcement(requested_class_id bigint, requested_title text, requested_body text)
returns bigint language plpgsql security definer set search_path='' as $$
declare announcement_id bigint; learner record;
begin
  if length(btrim(requested_title)) not between 1 and 160 or length(btrim(requested_body)) not between 1 and 5000 then raise exception using errcode='22023',message='Announcement title and message are required'; end if;
  perform 1 from public.classes where id=requested_class_id and status='active' and (owner_user_id=auth.uid() or public.is_platform_admin()) for update;
  if not found then raise exception 'Class is unavailable'; end if;
  insert into public.class_announcements(class_id,author_user_id,title,body) values(requested_class_id,auth.uid(),btrim(requested_title),btrim(requested_body)) returning id into announcement_id;
  for learner in select learner_user_id from public.class_enrollments where class_id=requested_class_id and status='active' loop perform public.create_class_announcement_notification(announcement_id,learner.learner_user_id); end loop;
  return announcement_id;
end; $$;

create or replace function public.get_class_announcements(requested_class_id bigint)
returns jsonb language sql stable security definer set search_path='' as $$
  select coalesce(jsonb_agg(row_data order by (row_data->>'publishedAt') desc),'[]'::jsonb)
  from (select jsonb_build_object('id',a.id,'classId',a.class_id,'title',a.title,'body',a.body,'revision',a.revision,'publishedAt',a.published_at,'editedAt',a.edited_at,'withdrawnAt',a.withdrawn_at,'readAt',r.read_at,'readRevision',r.read_revision,
      'readCount',(select count(*) from public.class_announcement_reads ar join public.class_enrollments ae on ae.learner_user_id=ar.learner_user_id and ae.class_id=a.class_id and ae.status='active' where ar.announcement_id=a.id and ar.read_revision>=a.revision),
      'activeLearners',(select count(*) from public.class_enrollments ae where ae.class_id=a.class_id and ae.status='active')) row_data
    from public.class_announcements a left join public.class_announcement_reads r on r.announcement_id=a.id and r.learner_user_id=auth.uid()
    where a.class_id=requested_class_id and a.withdrawn_at is null and (public.is_platform_admin() or exists(select 1 from public.classes c where c.id=a.class_id and c.owner_user_id=auth.uid()) or exists(select 1 from public.class_enrollments e where e.class_id=a.class_id and e.learner_user_id=auth.uid() and e.status='active'))) q;
$$;

create or replace function public.mark_class_announcement_read(requested_announcement_id bigint)
returns void language plpgsql security definer set search_path='' as $$
declare announcement_class_id bigint; current_revision integer;
begin
  select a.class_id,a.revision into announcement_class_id,current_revision from public.class_announcements a where a.id=requested_announcement_id and a.withdrawn_at is null;
  if announcement_class_id is null or not exists(select 1 from public.class_enrollments e where e.class_id=announcement_class_id and e.learner_user_id=auth.uid() and e.status='active') then raise exception 'Announcement is unavailable'; end if;
  insert into public.class_announcement_reads(announcement_id,learner_user_id,read_revision,read_at) values(requested_announcement_id,auth.uid(),current_revision,pg_catalog.now()) on conflict (announcement_id,learner_user_id) do update set read_revision=excluded.read_revision,read_at=excluded.read_at;
end; $$;

create or replace function public.mark_all_class_announcements_read(requested_class_id bigint)
returns void language sql security definer set search_path='' as $$
  insert into public.class_announcement_reads(announcement_id,learner_user_id,read_revision,read_at)
  select a.id,auth.uid(),a.revision,pg_catalog.now() from public.class_announcements a where a.class_id=requested_class_id and a.withdrawn_at is null and exists(select 1 from public.class_enrollments e where e.class_id=requested_class_id and e.learner_user_id=auth.uid() and e.status='active') on conflict (announcement_id,learner_user_id) do update set read_revision=excluded.read_revision,read_at=excluded.read_at;
$$;

create or replace function public.edit_class_announcement(requested_announcement_id bigint, requested_title text, requested_body text)
returns integer language plpgsql security definer set search_path='' as $$
declare next_revision integer; announcement_class_id bigint; learner record;
begin
  if length(btrim(requested_title)) not between 1 and 160 or length(btrim(requested_body)) not between 1 and 5000 then raise exception using errcode='22023',message='Announcement title and message are required'; end if;
  select a.class_id,a.revision into announcement_class_id,next_revision from public.class_announcements a where a.id=requested_announcement_id and a.withdrawn_at is null and (a.author_user_id=auth.uid() or exists(select 1 from public.classes c where c.id=a.class_id and c.owner_user_id=auth.uid()) or public.is_platform_admin()) for update;
  if announcement_class_id is null then raise exception 'Announcement is unavailable'; end if;
  if exists(select 1 from public.class_announcements a where a.id=requested_announcement_id and a.title=btrim(requested_title) and a.body=btrim(requested_body)) then return next_revision; end if;
  next_revision:=next_revision+1;
  update public.class_announcements set title=btrim(requested_title),body=btrim(requested_body),revision=next_revision,edited_at=pg_catalog.now(),updated_at=pg_catalog.now() where id=requested_announcement_id;
  for learner in select learner_user_id from public.class_enrollments where class_id=announcement_class_id and status='active' loop perform public.create_class_announcement_notification(requested_announcement_id,learner.learner_user_id,'announcement_updated','announcement:'||requested_announcement_id||':updated:'||next_revision::text); end loop;
  return next_revision;
end; $$;

create or replace function public.withdraw_class_announcement(requested_announcement_id bigint)
returns void language sql security definer set search_path='' as $$
  update public.class_announcements a set withdrawn_at=coalesce(a.withdrawn_at,pg_catalog.now()),updated_at=pg_catalog.now() where a.id=requested_announcement_id and (a.author_user_id=auth.uid() or exists(select 1 from public.classes c where c.id=a.class_id and c.owner_user_id=auth.uid()) or public.is_platform_admin());
$$;

create or replace function public.mark_notification_read(requested_notification_id bigint)
returns void language sql security definer set search_path='' as $$
  update public.learner_notifications n set read_at=coalesce(n.read_at,pg_catalog.now())
  where n.id=requested_notification_id and n.learner_user_id=auth.uid()
    and (n.announcement_id is null or public.is_active_class_announcement(n.announcement_id));
$$;
create or replace function public.mark_all_notifications_read()
returns void language sql security definer set search_path='' as $$
  update public.learner_notifications n set read_at=coalesce(n.read_at,pg_catalog.now())
  where n.learner_user_id=auth.uid() and n.read_at is null
    and (n.announcement_id is null or public.is_active_class_announcement(n.announcement_id));
$$;
create or replace function public.dismiss_notification(requested_notification_id bigint)
returns void language sql security definer set search_path='' as $$
  update public.learner_notifications n set dismissed_at=coalesce(n.dismissed_at,pg_catalog.now())
  where n.id=requested_notification_id and n.learner_user_id=auth.uid()
    and (n.announcement_id is null or public.is_active_class_announcement(n.announcement_id));
$$;
create or replace function public.clear_read_notifications()
returns void language sql security definer set search_path='' as $$
  update public.learner_notifications n set dismissed_at=coalesce(n.dismissed_at,pg_catalog.now())
  where n.learner_user_id=auth.uid() and n.read_at is not null and n.dismissed_at is null
    and (n.announcement_id is null or public.is_active_class_announcement(n.announcement_id));
$$;

create or replace function public.notify_enrollment_announcements()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.status='active' then perform public.backfill_class_announcement_notifications(new.class_id,new.learner_user_id); end if;
  return new;
end; $$;
create trigger class_enrollment_announcement_notifications after insert or update of status on public.class_enrollments for each row execute function public.notify_enrollment_announcements();

revoke all on public.class_announcements,public.class_announcement_reads from public,anon,authenticated;
revoke all on function public.create_class_announcement_notification(bigint,uuid,text,text),public.backfill_class_announcement_notifications(bigint,uuid),public.notify_enrollment_announcements() from public,anon,authenticated;
revoke all on function public.is_active_class_announcement(bigint) from public,anon;
grant execute on function public.is_active_class_announcement(bigint) to authenticated;
revoke all on function public.publish_class_announcement(bigint,text,text),public.get_class_announcements(bigint),public.mark_class_announcement_read(bigint),public.mark_all_class_announcements_read(bigint),public.edit_class_announcement(bigint,text,text),public.withdraw_class_announcement(bigint) from public,anon;
grant execute on function public.publish_class_announcement(bigint,text,text),public.get_class_announcements(bigint),public.mark_class_announcement_read(bigint),public.mark_all_class_announcements_read(bigint),public.edit_class_announcement(bigint,text,text),public.withdraw_class_announcement(bigint) to authenticated;

commit;
