begin;

create type public.class_course_assignment_status as enum ('active','inactive');

create table public.class_course_assignments (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete restrict,
  course_release_id bigint not null references public.course_releases(id) on delete restrict,
  source_course_id bigint not null references public.courses(id) on delete restrict,
  assigned_by uuid not null references auth.users(id) on delete restrict,
  status public.class_course_assignment_status not null default 'active',
  assigned_at timestamptz not null default pg_catalog.now(),
  ended_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  check ((status='active' and ended_at is null) or status='inactive')
);
create unique index class_course_assignments_one_active_course
  on public.class_course_assignments(class_id,source_course_id) where status='active';
create index class_course_assignments_release_idx on public.class_course_assignments(course_release_id,status);

alter table public.class_course_assignments enable row level security;
grant select on public.class_course_assignments to authenticated;
create policy class_assignments_select_authorized on public.class_course_assignments for select to authenticated using (
  public.owns_class(class_id) or (
    status='active' and public.has_active_class_enrollment(class_id)
    and exists(select 1 from public.classes c where c.id=class_id and c.status='active')
  )
);

create or replace function public.can_access_course_release(requested_release_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.course_releases r where r.id=requested_release_id and (r.owner_user_id=auth.uid() or public.is_platform_admin()))
    or (public.is_learner_identity() and (
      exists(select 1 from public.course_release_learner_entitlements e where e.course_release_id=requested_release_id and e.learner_id=auth.uid())
      or exists(
        select 1 from public.class_course_assignments a
        join public.classes c on c.id=a.class_id and c.status='active'
        join public.class_enrollments e on e.class_id=c.id and e.status='active'
        where a.course_release_id=requested_release_id and a.status='active' and e.learner_user_id=auth.uid()
      )
    ));
$$;

create or replace function public.list_assignable_course_releases()
returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
  if not (public.is_content_teacher() or public.is_platform_admin()) then raise exception 'Teacher access is required'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
    'releaseId',r.id,'courseId',r.course_id,'courseTitle',r.course_title,'courseDescription',r.course_description,
    'courseLevel',r.course_level,'releaseNumber',r.release_number,'releasedAt',r.released_at,
    'isLatest',r.release_number=(select max(n.release_number) from public.course_releases n where n.course_id=r.course_id)
  ) order by r.course_title,r.release_number desc)
  from public.course_releases r where r.owner_user_id=auth.uid() or public.is_platform_admin()),'[]'::jsonb);
end; $$;

create or replace function public.assign_class_course_release(requested_class_id bigint,requested_release_id bigint)
returns bigint language plpgsql security definer set search_path='' as $$
declare release_row record; current_id bigint; created_id bigint;
begin
  select * into release_row from public.course_releases where id=requested_release_id;
  if release_row.id is null then raise exception 'Course Release is unavailable'; end if;
  perform 1 from public.classes where id=requested_class_id and status='active' and (owner_user_id=auth.uid() or public.is_platform_admin()) for update;
  if not found then raise exception 'Active Class is unavailable'; end if;
  if release_row.owner_user_id<>auth.uid() and not public.is_platform_admin() then raise exception 'Course Release is unavailable'; end if;
  select id into current_id from public.class_course_assignments
    where class_id=requested_class_id and source_course_id=release_row.course_id and status='active' for update;
  if current_id is not null and exists(select 1 from public.class_course_assignments where id=current_id and course_release_id=requested_release_id) then return current_id; end if;
  update public.class_course_assignments set status='inactive',ended_at=pg_catalog.now(),updated_at=pg_catalog.now()
    where id=current_id;
  insert into public.class_course_assignments(class_id,course_release_id,source_course_id,assigned_by)
    values(requested_class_id,requested_release_id,release_row.course_id,auth.uid()) returning id into created_id;
  return created_id;
end; $$;

create or replace function public.deactivate_class_course_assignment(requested_assignment_id bigint)
returns void language plpgsql security definer set search_path='' as $$
begin
  update public.class_course_assignments a set status='inactive',ended_at=coalesce(ended_at,pg_catalog.now()),updated_at=pg_catalog.now()
  where a.id=requested_assignment_id and a.status='active' and public.owns_class(a.class_id);
  if not found and not exists(select 1 from public.class_course_assignments a where a.id=requested_assignment_id and a.status='inactive' and public.owns_class(a.class_id)) then raise exception 'Assignment is unavailable'; end if;
end; $$;

create or replace function public.get_class_course_assignments(requested_class_id bigint)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare staff_access boolean:=public.owns_class(requested_class_id); learner_access boolean;
begin
  select exists(select 1 from public.classes c join public.class_enrollments e on e.class_id=c.id
    where c.id=requested_class_id and c.status='active' and e.learner_user_id=auth.uid() and e.status='active') into learner_access;
  if not staff_access and not (public.is_learner_identity() and learner_access) then raise exception 'Class is unavailable'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
    'assignmentId',a.id,'classId',a.class_id,'releaseId',a.course_release_id,'courseId',a.source_course_id,
    'courseTitle',r.course_title,'courseDescription',r.course_description,'courseLevel',r.course_level,
    'releaseNumber',r.release_number,'assignedAt',a.assigned_at,'endedAt',a.ended_at,'status',a.status,
    'latestReleaseNumber',(select max(n.release_number) from public.course_releases n where n.course_id=a.source_course_id)
  ) order by a.status,a.assigned_at desc)
  from public.class_course_assignments a join public.course_releases r on r.id=a.course_release_id
  where a.class_id=requested_class_id and (staff_access or a.status='active')),'[]'::jsonb);
end; $$;

create or replace function public.get_class_assignment_progress(requested_assignment_id bigint)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare assignment_row record; total_lessons integer;
begin
  select a.*,r.course_title,r.release_number into assignment_row
  from public.class_course_assignments a join public.course_releases r on r.id=a.course_release_id
  where a.id=requested_assignment_id;
  if assignment_row.id is null or not public.owns_class(assignment_row.class_id) then raise exception 'Assignment is unavailable'; end if;
  select count(*) into total_lessons from public.course_release_lessons l join public.course_release_units u on u.id=l.course_release_unit_id where u.course_release_id=assignment_row.course_release_id;
  return jsonb_build_object('assignmentId',assignment_row.id,'releaseId',assignment_row.course_release_id,
    'courseTitle',assignment_row.course_title,'releaseNumber',assignment_row.release_number,'totalLessons',total_lessons,
    'learners',coalesce((select jsonb_agg(jsonb_build_object(
      'learnerId',e.learner_user_id,'email',u.email,
      'startedLessons',(select count(*) from public.learner_release_lesson_progress p join public.course_release_lessons l on l.id=p.course_release_lesson_id join public.course_release_units ru on ru.id=l.course_release_unit_id where p.learner_id=e.learner_user_id and ru.course_release_id=assignment_row.course_release_id),
      'completedLessons',(select count(*) from public.learner_release_lesson_progress p join public.course_release_lessons l on l.id=p.course_release_lesson_id join public.course_release_units ru on ru.id=l.course_release_unit_id where p.learner_id=e.learner_user_id and ru.course_release_id=assignment_row.course_release_id and p.completed_at is not null),
      'completionPercent',case when total_lessons=0 then 0 else round(100.0*(select count(*) from public.learner_release_lesson_progress p join public.course_release_lessons l on l.id=p.course_release_lesson_id join public.course_release_units ru on ru.id=l.course_release_unit_id where p.learner_id=e.learner_user_id and ru.course_release_id=assignment_row.course_release_id and p.completed_at is not null)/total_lessons) end,
      'lastAccessedAt',(select max(p.last_accessed_at) from public.learner_release_lesson_progress p join public.course_release_lessons l on l.id=p.course_release_lesson_id join public.course_release_units ru on ru.id=l.course_release_unit_id where p.learner_id=e.learner_user_id and ru.course_release_id=assignment_row.course_release_id)
    ) order by u.email) from public.class_enrollments e join auth.users u on u.id=e.learner_user_id where e.class_id=assignment_row.class_id and e.status='active'),'[]'::jsonb));
end; $$;

revoke all on table public.class_course_assignments from anon;
revoke all on function public.list_assignable_course_releases(),public.assign_class_course_release(bigint,bigint),public.deactivate_class_course_assignment(bigint),public.get_class_course_assignments(bigint),public.get_class_assignment_progress(bigint) from public,anon;
grant execute on function public.list_assignable_course_releases(),public.assign_class_course_release(bigint,bigint),public.deactivate_class_course_assignment(bigint),public.get_class_course_assignments(bigint),public.get_class_assignment_progress(bigint) to authenticated;
revoke all on function public.can_access_course_release(bigint) from public,anon,authenticated;

commit;
