begin;

alter type public.lesson_activity_type
  add value if not exists 'interactive_practice';

create table public.interactive_practice_exercises (
  id bigint generated by default as identity primary key,
  activity_id bigint not null unique
    references public.lesson_activities(id) on delete cascade,
  mode text not null
    check (
      mode in (
        'multiple_choice',
        'true_false',
        'match',
        'fill_blank'
      )
    ),
  instructions text,
  explanation text,
  config jsonb not null default '{}'::jsonb
    check (jsonb_typeof(config) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.interactive_practice_exercises
  enable row level security;

grant select
  on public.interactive_practice_exercises
  to authenticated;
grant usage, select
  on sequence public.interactive_practice_exercises_id_seq
  to authenticated;

create policy "staff read interactive practice"
  on public.interactive_practice_exercises
  for select
  to authenticated
  using (public.can_manage_content());

create or replace function
  public.interactive_practice_is_complete(
    requested_mode text,
    requested_config jsonb
  )
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  complete_count integer;
  correct_count integer;
begin
  if jsonb_typeof(requested_config) <> 'object'
    or nullif(
      btrim(requested_config ->> 'prompt'),
      ''
    ) is null
  then
    return false;
  end if;

  if requested_mode = 'multiple_choice' then
    if jsonb_typeof(requested_config -> 'options')
      <> 'array'
    then
      return false;
    end if;

    select
      count(*) filter (
        where jsonb_typeof(option_value) = 'object'
          and nullif(
            btrim(option_value ->> 'text'),
            ''
          ) is not null
      ),
      count(*) filter (
        where jsonb_typeof(option_value) = 'object'
          and nullif(
            btrim(option_value ->> 'text'),
            ''
          ) is not null
          and jsonb_typeof(
            option_value -> 'correct'
          ) = 'boolean'
          and (option_value ->> 'correct')::boolean
      )
    into complete_count, correct_count
    from jsonb_array_elements(
      requested_config -> 'options'
    ) as option_value;

    return complete_count >= 2
      and correct_count = 1;
  end if;

  if requested_mode = 'true_false' then
    return jsonb_typeof(
      requested_config -> 'correctAnswer'
    ) = 'boolean';
  end if;

  if requested_mode = 'match' then
    if jsonb_typeof(requested_config -> 'pairs')
      <> 'array'
    then
      return false;
    end if;

    select count(*)
    into complete_count
    from jsonb_array_elements(
      requested_config -> 'pairs'
    ) as pair_value
    where jsonb_typeof(pair_value) = 'object'
      and nullif(
        btrim(pair_value ->> 'left'),
        ''
      ) is not null
      and nullif(
        btrim(pair_value ->> 'right'),
        ''
      ) is not null;

    return complete_count >= 2;
  end if;

  if requested_mode = 'fill_blank' then
    if jsonb_typeof(
      requested_config -> 'acceptedAnswers'
    ) <> 'array'
    then
      return false;
    end if;

    select count(*)
    into complete_count
    from jsonb_array_elements(
      requested_config -> 'acceptedAnswers'
    ) as answer_value
    where jsonb_typeof(answer_value) = 'string'
      and nullif(
        btrim(answer_value #>> '{}'),
        ''
      ) is not null;

    return complete_count >= 1;
  end if;

  return false;
end;
$$;

create or replace function
  public.validate_lesson_version_interactive_practice(
    requested_lesson_version_id bigint
  )
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  invalid_activity_id bigint;
begin
  select activity.id
  into invalid_activity_id
  from public.lesson_activities activity
  left join public.interactive_practice_exercises exercise
    on exercise.activity_id = activity.id
  where activity.lesson_version_id =
      requested_lesson_version_id
    and activity.type = 'interactive_practice'
    and (
      exercise.id is null
      or not public.interactive_practice_is_complete(
        exercise.mode,
        exercise.config
      )
  )
  order by activity.id
  limit 1
  for update of activity;

  if found then
    raise exception
      'Invalid publication content: Interactive Practice activity % is incomplete',
      invalid_activity_id;
  end if;

  select activity.id
  into invalid_activity_id
  from public.lesson_activities activity
  where activity.lesson_version_id =
      requested_lesson_version_id
    and activity.type = 'interactive_practice'
  order by activity.id
  limit 1
  for update of activity;

  if found then
    raise exception
      'Interactive Practice activity % cannot be published until learner delivery is available',
      invalid_activity_id;
  end if;
end;
$$;

create or replace function
  public.create_draft_interactive_practice(
    requested_lesson_version_id bigint,
    requested_title text
  )
returns public.lesson_activities
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.lesson_activities;
  next_position integer;
begin
  perform public.lock_content_hierarchy_gate();

  if not public.can_edit_drafts() then
    raise exception 'Draft editing permission is required';
  end if;

  perform 1
  from public.lesson_versions version
  join public.lessons lesson
    on lesson.id = version.lesson_id
  join public.units unit
    on unit.id = lesson.unit_id
  join public.courses course
    on course.id = unit.course_id
  where version.id = requested_lesson_version_id
    and version.status = 'draft'
    and lesson.status = 'draft'
    and unit.status = 'draft'
    and course.status = 'draft'
  for update of version, lesson, unit, course;

  if not found then
    raise exception 'Draft hierarchy unavailable';
  end if;

  perform 1
  from public.lesson_activities
  where lesson_version_id =
    requested_lesson_version_id
  order by id
  for update;

  select coalesce(max(position), -1) + 1
  into next_position
  from public.lesson_activities
  where lesson_version_id =
    requested_lesson_version_id;

  insert into public.lesson_activities (
    lesson_version_id,
    type,
    title,
    position,
    required
  )
  values (
    requested_lesson_version_id,
    'interactive_practice',
    btrim(requested_title),
    next_position,
    true
  )
  returning * into result;

  insert into public.interactive_practice_exercises (
    activity_id,
    mode,
    config
  )
  values (
    result.id,
    'multiple_choice',
    '{
      "prompt": "",
      "options": [],
      "correctAnswer": null,
      "pairs": [],
      "acceptedAnswers": []
    }'::jsonb
  );

  return result;
end;
$$;

create or replace function
  public.save_draft_interactive_practice(
    requested_activity_id bigint,
    expected_updated_at timestamptz,
    requested_mode text,
    requested_instructions text,
    requested_explanation text,
    requested_config jsonb
  )
returns public.interactive_practice_exercises
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.interactive_practice_exercises;
begin
  perform public.lock_content_hierarchy_gate();

  if not public.can_edit_drafts() then
    raise exception 'Draft editing permission is required';
  end if;

  update public.interactive_practice_exercises exercise
  set mode = requested_mode,
    instructions = nullif(
      btrim(requested_instructions),
      ''
    ),
    explanation = nullif(
      btrim(requested_explanation),
      ''
    ),
    config = requested_config,
    updated_at = clock_timestamp()
  from public.lesson_activities activity
  join public.lesson_versions version
    on version.id = activity.lesson_version_id
  join public.lessons lesson
    on lesson.id = version.lesson_id
  join public.units unit
    on unit.id = lesson.unit_id
  join public.courses course
    on course.id = unit.course_id
  where exercise.activity_id =
      requested_activity_id
    and activity.id = exercise.activity_id
    and activity.type = 'interactive_practice'
    and version.status = 'draft'
    and lesson.status = 'draft'
    and unit.status = 'draft'
    and course.status = 'draft'
    and exercise.updated_at = expected_updated_at
  returning exercise.* into result;

  if not found then
    raise exception
      'Interactive Practice changed or is unavailable';
  end if;

  return result;
end;
$$;

create or replace function
  public.duplicate_draft_interactive_practice(
    requested_activity_id bigint,
    expected_lesson_version_id bigint
  )
returns public.lesson_activities
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_activity public.lesson_activities;
  source_exercise public.interactive_practice_exercises;
  result public.lesson_activities;
  next_position integer;
begin
  perform public.lock_content_hierarchy_gate();

  if not public.can_edit_drafts() then
    raise exception 'Draft editing permission is required';
  end if;

  select activity.*
  into source_activity
  from public.lesson_activities activity
  join public.interactive_practice_exercises exercise
    on exercise.activity_id = activity.id
  join public.lesson_versions version
    on version.id = activity.lesson_version_id
  join public.lessons lesson
    on lesson.id = version.lesson_id
  join public.units unit
    on unit.id = lesson.unit_id
  join public.courses course
    on course.id = unit.course_id
  where activity.id = requested_activity_id
    and activity.lesson_version_id =
      expected_lesson_version_id
    and activity.type = 'interactive_practice'
    and version.status = 'draft'
    and lesson.status = 'draft'
    and unit.status = 'draft'
    and course.status = 'draft'
  for update of
    activity,
    exercise,
    version,
    lesson,
    unit,
    course;

  if not found then
    raise exception
      'The expected draft Interactive Practice is unavailable';
  end if;

  select *
  into strict source_exercise
  from public.interactive_practice_exercises
  where activity_id = source_activity.id;

  perform 1
  from public.lesson_activities
  where lesson_version_id =
    expected_lesson_version_id
  order by id
  for update;

  select coalesce(max(position), -1) + 1
  into next_position
  from public.lesson_activities
  where lesson_version_id =
    expected_lesson_version_id;

  insert into public.lesson_activities (
    lesson_version_id,
    type,
    title,
    position,
    required
  )
  values (
    expected_lesson_version_id,
    source_activity.type,
    source_activity.title || ' copy',
    next_position,
    source_activity.required
  )
  returning * into result;

  insert into public.interactive_practice_exercises (
    activity_id,
    mode,
    instructions,
    explanation,
    config
  )
  values (
    result.id,
    source_exercise.mode,
    source_exercise.instructions,
    source_exercise.explanation,
    source_exercise.config
  );

  return result;
end;
$$;

create or replace function
  public.publish_lesson_version(
    requested_lesson_version_id bigint
  )
returns public.lesson_versions
language plpgsql
security definer
set search_path = ''
as $$
declare
  version_row public.lesson_versions%rowtype;
  published_version public.lesson_versions%rowtype;
begin
  if not public.can_publish_content() then
    raise exception
      'Publisher or administrator role required';
  end if;

  perform public.lock_content_hierarchy_gate();

  select *
  into version_row
  from public.lesson_versions
  where id = requested_lesson_version_id
  for update;

  if not found then
    raise exception 'Lesson version does not exist';
  end if;

  if version_row.status <> 'draft' then
    raise exception
      'Only a draft lesson version can be published';
  end if;

  perform public.validate_lesson_version_listening_audio(
    version_row.id
  );
  perform public.validate_lesson_version_pronunciation_blocks(
    version_row.id
  );
  perform public.validate_lesson_version_media(
    version_row.id
  );
  perform public.validate_lesson_version_ai_missions(
    version_row.id
  );
  perform public.validate_lesson_version_interactive_practice(
    version_row.id
  );

  perform pg_catalog.set_config(
    'pronouncelab.lesson_publication',
    'on',
    true
  );

  update public.lesson_versions
  set status = 'published',
    published_by = auth.uid(),
    published_at = now()
  where id = version_row.id
    and status = 'draft'
  returning * into published_version;

  if not found then
    raise exception
      'Lesson version changed during publication';
  end if;

  return published_version;
end;
$$;

revoke all on function
  public.interactive_practice_is_complete(text, jsonb)
  from public, anon, authenticated;
revoke all on function
  public.validate_lesson_version_interactive_practice(bigint)
  from public, anon, authenticated;
revoke all on function
  public.create_draft_interactive_practice(bigint, text)
  from public, anon;
grant execute on function
  public.create_draft_interactive_practice(bigint, text)
  to authenticated;
revoke all on function
  public.save_draft_interactive_practice(
    bigint,
    timestamptz,
    text,
    text,
    text,
    jsonb
  )
  from public, anon;
grant execute on function
  public.save_draft_interactive_practice(
    bigint,
    timestamptz,
    text,
    text,
    text,
    jsonb
  )
  to authenticated;
revoke all on function
  public.duplicate_draft_interactive_practice(
    bigint,
    bigint
  )
  from public, anon;
grant execute on function
  public.duplicate_draft_interactive_practice(
    bigint,
    bigint
  )
  to authenticated;
revoke all on function
  public.publish_lesson_version(bigint)
  from public;
grant execute on function
  public.publish_lesson_version(bigint)
  to authenticated;

commit;
