begin;

create extension if not exists pgcrypto
  with schema extensions;

create type public.content_status as enum (
  'draft',
  'published',
  'unpublished',
  'archived'
);

create type public.lesson_version_status as enum (
  'draft',
  'published',
  'archived'
);

create type public.lesson_activity_type as enum (
  'theory',
  'listening',
  'pronunciation',
  'practice',
  'quiz'
);

create type public.media_kind as enum (
  'audio',
  'image'
);

create type public.admin_role as enum (
  'editor',
  'publisher',
  'admin'
);

create table public.profiles (
  id uuid primary key
    references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  user_id uuid not null
    references auth.users (id) on delete cascade,
  role public.admin_role not null,
  created_at timestamptz not null default now(),
  created_by uuid
    references auth.users (id) on delete set null,
  primary key (user_id, role)
);

create table public.courses (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null default '',
  level text not null default '',
  emoji text not null default '',
  position integer not null default 0
    check (position >= 0),
  status public.content_status not null default 'draft',
  published_at timestamptz,
  created_by uuid
    references auth.users (id) on delete set null,
  updated_by uuid
    references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint courses_slug_not_blank
    check (char_length(btrim(slug)) > 0),
  constraint courses_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint courses_published_at_required
    check (
      status <> 'published'
      or published_at is not null
    ),
  constraint courses_position_unique unique (position)
);

create table public.units (
  id bigint generated by default as identity primary key,
  course_id bigint not null
    references public.courses (id) on delete cascade,
  title text not null,
  description text not null default '',
  position integer not null default 0
    check (position >= 0),
  status public.content_status not null default 'draft',
  published_at timestamptz,
  created_by uuid
    references auth.users (id) on delete set null,
  updated_by uuid
    references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint units_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint units_published_at_required
    check (
      status <> 'published'
      or published_at is not null
    ),
  constraint units_course_position_unique
    unique (course_id, position)
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  unit_id bigint not null
    references public.units (id) on delete cascade,
  title text not null,
  description text not null default '',
  position integer not null default 0
    check (position >= 0),
  status public.content_status not null default 'draft',
  current_published_version_id bigint,
  published_at timestamptz,
  created_by uuid
    references auth.users (id) on delete set null,
  updated_by uuid
    references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lessons_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint lessons_published_at_required
    check (
      status <> 'published'
      or published_at is not null
    ),
  constraint lessons_unit_position_unique
    unique (unit_id, position)
);

create table public.lesson_versions (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null
    references public.lessons (id) on delete cascade,
  version_number integer not null
    check (version_number > 0),
  status public.lesson_version_status not null default 'draft',
  created_by uuid
    references auth.users (id) on delete set null,
  published_by uuid
    references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint lesson_versions_published_at_required
    check (
      status <> 'published'
      or published_at is not null
    ),
  constraint lesson_versions_number_unique
    unique (lesson_id, version_number)
);

alter table public.lessons
  add constraint lessons_current_published_version_fk
  foreign key (current_published_version_id)
  references public.lesson_versions (id)
  on delete set null
  deferrable initially deferred;

create unique index lesson_versions_one_published
  on public.lesson_versions (lesson_id)
  where status = 'published';

create table public.lesson_activities (
  id bigint generated by default as identity primary key,
  lesson_version_id bigint not null
    references public.lesson_versions (id) on delete cascade,
  type public.lesson_activity_type not null,
  title text not null,
  position integer not null default 0
    check (position >= 0),
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_activities_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint lesson_activities_version_position_unique
    unique (lesson_version_id, position)
);

create table public.media_assets (
  id uuid primary key
    default extensions.gen_random_uuid(),
  kind public.media_kind not null,
  bucket text not null,
  object_path text not null,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null
    check (size_bytes >= 0),
  alt_text text,
  status public.content_status not null default 'draft',
  uploaded_by uuid
    references auth.users (id) on delete set null,
  published_by uuid
    references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint media_assets_bucket_path_unique
    unique (bucket, object_path),
  constraint media_assets_path_not_blank
    check (char_length(btrim(object_path)) > 0),
  constraint media_assets_kind_bucket_match
    check (
      (
        kind = 'audio'
        and bucket in (
          'content-audio-drafts',
          'content-audio'
        )
      )
      or (
        kind = 'image'
        and bucket in (
          'content-image-drafts',
          'content-images'
        )
      )
    ),
  constraint media_assets_status_bucket_match
    check (
      (
        status = 'draft'
        and bucket in (
          'content-audio-drafts',
          'content-image-drafts'
        )
      )
      or (
        status = 'published'
        and bucket in (
          'content-audio',
          'content-images'
        )
      )
      or status in (
        'unpublished',
        'archived'
      )
    ),
  constraint media_assets_published_at_required
    check (
      status <> 'published'
      or published_at is not null
    )
);

create table public.theory_blocks (
  id bigint generated by default as identity primary key,
  activity_id bigint not null
    references public.lesson_activities (id) on delete cascade,
  block_type text not null
    check (
      block_type in (
        'heading',
        'paragraph',
        'tip',
        'example',
        'image',
        'audio'
      )
    ),
  position integer not null default 0
    check (position >= 0),
  heading_level smallint
    check (heading_level between 1 and 3),
  title text,
  text text,
  media_asset_id uuid
    references public.media_assets (id) on delete restrict,
  alt_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint theory_blocks_activity_position_unique
    unique (activity_id, position)
);

create table public.listening_items (
  id bigint generated by default as identity primary key,
  activity_id bigint not null
    references public.lesson_activities (id) on delete cascade,
  title text not null,
  instructions text,
  transcript text,
  audio_asset_id uuid
    references public.media_assets (id) on delete restrict,
  position integer not null default 0
    check (position >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listening_items_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint listening_items_activity_position_unique
    unique (activity_id, position)
);

create table public.pronunciation_items (
  id bigint generated by default as identity primary key,
  activity_id bigint not null
    references public.lesson_activities (id) on delete cascade,
  title text not null,
  instructions text,
  display_text text not null default '',
  audio_asset_id uuid
    references public.media_assets (id) on delete restrict,
  position integer not null default 0
    check (position >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pronunciation_items_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint pronunciation_items_activity_position_unique
    unique (activity_id, position)
);

create table public.assessment_sets (
  id bigint generated by default as identity primary key,
  activity_id bigint not null
    references public.lesson_activities (id) on delete cascade,
  listening_item_id bigint
    references public.listening_items (id) on delete cascade,
  title text not null,
  instructions text,
  position integer not null default 0
    check (position >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assessment_sets_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint assessment_sets_activity_position_unique
    unique (activity_id, position)
);

create table public.questions (
  id bigint generated by default as identity primary key,
  assessment_set_id bigint not null
    references public.assessment_sets (id) on delete cascade,
  prompt text not null,
  explanation text,
  position integer not null default 0
    check (position >= 0),
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint questions_prompt_not_blank
    check (char_length(btrim(prompt)) > 0),
  constraint questions_set_position_unique
    unique (assessment_set_id, position)
);

create table public.question_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null
    references public.questions (id) on delete cascade,
  text text not null,
  position integer not null default 0
    check (position >= 0),
  is_correct boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint question_options_text_not_blank
    check (char_length(btrim(text)) > 0),
  constraint question_options_question_position_unique
    unique (question_id, position)
);

create unique index question_options_one_correct
  on public.question_options (question_id)
  where is_correct;

create index units_course_id_idx
  on public.units (course_id);
create index lessons_unit_id_idx
  on public.lessons (unit_id);
create index lessons_current_version_idx
  on public.lessons (current_published_version_id);
create index lesson_versions_lesson_id_idx
  on public.lesson_versions (lesson_id);
create index lesson_activities_version_id_idx
  on public.lesson_activities (lesson_version_id);
create index theory_blocks_activity_id_idx
  on public.theory_blocks (activity_id);
create index listening_items_activity_id_idx
  on public.listening_items (activity_id);
create index pronunciation_items_activity_id_idx
  on public.pronunciation_items (activity_id);
create index assessment_sets_activity_id_idx
  on public.assessment_sets (activity_id);
create index assessment_sets_listening_item_id_idx
  on public.assessment_sets (listening_item_id);
create index questions_assessment_set_id_idx
  on public.questions (assessment_set_id);
create index question_options_question_id_idx
  on public.question_options (question_id);
create index media_assets_status_kind_idx
  on public.media_assets (status, kind);
create index user_roles_role_idx
  on public.user_roles (role);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.validate_lesson_publication()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.current_published_version_id is not null
    and not exists (
      select 1
      from public.lesson_versions
      where lesson_versions.id =
        new.current_published_version_id
        and lesson_versions.lesson_id = new.id
    )
  then
    raise exception
      'Current published version must belong to the lesson';
  end if;

  if new.status = 'published'
    and (
      new.current_published_version_id is null
      or not exists (
        select 1
        from public.lesson_versions
        where lesson_versions.id =
          new.current_published_version_id
          and lesson_versions.lesson_id = new.id
          and lesson_versions.status = 'published'
      )
    )
  then
    raise exception
      'Published lessons require an active published version';
  end if;

  return new;
end;
$$;

create or replace function public.protect_published_lesson_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.status = 'draft'
    and new.status = 'published'
    and (
      new.lesson_id is distinct from old.lesson_id
      or new.version_number is distinct from old.version_number
      or new.created_by is distinct from old.created_by
      or new.created_at is distinct from old.created_at
    )
  then
    raise exception
      'Publishing cannot rewrite lesson version identity';
  end if;

  if old.status in (
    'published',
    'archived'
  )
    and (
      new.lesson_id is distinct from old.lesson_id
      or new.version_number is distinct from old.version_number
      or new.created_by is distinct from old.created_by
      or new.created_at is distinct from old.created_at
      or new.published_by is distinct from old.published_by
      or new.published_at is distinct from old.published_at
    )
  then
    raise exception
      'Published lesson versions are immutable';
  end if;

  if old.status in (
    'published',
    'archived'
  )
    and new.status not in (
      'published',
      'archived'
    )
  then
    raise exception
      'Published or archived lesson versions cannot return to draft';
  end if;

  return new;
end;
$$;

create or replace function public.validate_version_publication_reference()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status <> 'published'
    and exists (
      select 1
      from public.lessons
      where lessons.current_published_version_id =
        new.id
        and lessons.status = 'published'
    )
  then
    raise exception
      'A published lesson cannot reference an unpublished version';
  end if;

  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger courses_set_updated_at
before update on public.courses
for each row execute function public.set_updated_at();

create trigger units_set_updated_at
before update on public.units
for each row execute function public.set_updated_at();

create trigger lessons_set_updated_at
before update on public.lessons
for each row execute function public.set_updated_at();

create constraint trigger lessons_validate_publication
after insert or update on public.lessons
deferrable initially deferred
for each row
execute function public.validate_lesson_publication();

create trigger lesson_versions_set_updated_at
before update on public.lesson_versions
for each row execute function public.set_updated_at();

create trigger lesson_versions_protect_published
before update on public.lesson_versions
for each row
execute function public.protect_published_lesson_version();

create constraint trigger lesson_versions_validate_reference
after update on public.lesson_versions
deferrable initially deferred
for each row
execute function public.validate_version_publication_reference();

create trigger lesson_activities_set_updated_at
before update on public.lesson_activities
for each row execute function public.set_updated_at();

create trigger media_assets_set_updated_at
before update on public.media_assets
for each row execute function public.set_updated_at();

create trigger theory_blocks_set_updated_at
before update on public.theory_blocks
for each row execute function public.set_updated_at();

create trigger listening_items_set_updated_at
before update on public.listening_items
for each row execute function public.set_updated_at();

create trigger pronunciation_items_set_updated_at
before update on public.pronunciation_items
for each row execute function public.set_updated_at();

create trigger assessment_sets_set_updated_at
before update on public.assessment_sets
for each row execute function public.set_updated_at();

create trigger questions_set_updated_at
before update on public.questions
for each row execute function public.set_updated_at();

create trigger question_options_set_updated_at
before update on public.question_options
for each row execute function public.set_updated_at();

commit;
