begin;

create table public.learner_notifications (
  id bigint generated by default as identity primary key,
  learner_user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null check (notification_type in ('new_assignment','assignment_available','due_soon','assignment_late')),
  class_id bigint not null references public.classes(id) on delete restrict,
  assignment_id bigint not null references public.class_course_assignments(id) on delete restrict,
  course_release_id bigint not null references public.course_releases(id) on delete restrict,
  title text not null,
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default pg_catalog.now(),
  read_at timestamptz,
  event_key text not null,
  unique (learner_user_id, event_key)
);
create index learner_notifications_inbox_idx on public.learner_notifications(learner_user_id, read_at, created_at desc);
alter table public.learner_notifications enable row level security;
create policy learner_notifications_select_own on public.learner_notifications for select to authenticated using (learner_user_id=auth.uid());
grant select on public.learner_notifications to authenticated;

create or replace function public.create_assignment_notification(
  requested_assignment_id bigint,
  requested_learner_id uuid,
  requested_type text,
  requested_event_key text
) returns bigint language plpgsql security definer set search_path='' as $$
declare assignment_row record; notification_id bigint;
begin
  select a.*,r.course_title,r.id as release_id,c.name as class_name,c.timezone as class_timezone into assignment_row
  from public.class_course_assignments a join public.course_releases r on r.id=a.course_release_id join public.classes c on c.id=a.class_id
  where a.id=requested_assignment_id;
  if assignment_row.id is null or requested_type not in ('new_assignment','assignment_available','due_soon','assignment_late') then return null; end if;
  if not exists(select 1 from public.class_enrollments e where e.class_id=assignment_row.class_id and e.learner_user_id=requested_learner_id and e.status='active') then return null; end if;
  insert into public.learner_notifications(learner_user_id,notification_type,class_id,assignment_id,course_release_id,title,body,metadata,event_key)
  values(requested_learner_id,requested_type,assignment_row.class_id,assignment_row.id,assignment_row.release_id,
    case requested_type when 'new_assignment' then 'New assignment' when 'assignment_available' then 'Assignment available' when 'due_soon' then 'Due soon' else 'Assignment late' end,
    case requested_type when 'new_assignment' then assignment_row.course_title||' was assigned in '||assignment_row.class_name||'.'
      when 'assignment_available' then assignment_row.course_title||' is now available.'
      when 'due_soon' then assignment_row.course_title||' is due '||to_char(assignment_row.due_at at time zone assignment_row.class_timezone,'FMMonth FMDD, YYYY at FMHH12:MI AM')||'.'
      else assignment_row.course_title||' is past due. You can still complete it.' end,
    jsonb_build_object('courseTitle',assignment_row.course_title,'className',assignment_row.class_name,'dueAt',assignment_row.due_at,'availableAt',assignment_row.available_at),requested_event_key)
  on conflict (learner_user_id,event_key) do nothing returning id into notification_id;
  return notification_id;
end; $$;

create or replace function public.notify_assignment_learners(requested_assignment_id bigint)
returns void language plpgsql security definer set search_path='' as $$
declare assignment_row record; enrollment_row record;
begin
  select * into assignment_row from public.class_course_assignments where id=requested_assignment_id and status='active';
  if assignment_row.id is null then return; end if;
  for enrollment_row in select learner_user_id from public.class_enrollments where class_id=assignment_row.class_id and status='active' loop
    perform public.create_assignment_notification(assignment_row.id,enrollment_row.learner_user_id,'new_assignment','assignment:'||assignment_row.id||':new');
  end loop;
end; $$;

-- Extend the deployed scheduling RPC from this forward migration. The prior
-- migration remains immutable; new assignments now emit their event after the
-- assignment row is committed in the same transaction, while Release updates
-- continue to project progress without creating a fake new assignment event.
create or replace function public.assign_class_course_release(
  requested_class_id bigint,
  requested_release_id bigint,
  requested_available_at timestamptz,
  requested_due_at timestamptz
) returns bigint language plpgsql security definer set search_path='' as $$
declare release_row record; current_row record; created_id bigint;
begin
  if requested_due_at is not null and requested_available_at is not null and requested_due_at <= requested_available_at then
    raise exception using errcode='22023', message='Due date must be after availability';
  end if;
  if requested_due_at is not null and requested_available_at is null and requested_due_at <= pg_catalog.now() then
    raise exception using errcode='22023', message='Due date must be in the future';
  end if;
  select r.*,c.status as source_course_status into release_row from public.course_releases r join public.courses c on c.id=r.course_id where r.id=requested_release_id;
  if release_row.id is null or release_row.source_course_status='archived' then raise exception 'Course Release is unavailable'; end if;
  perform 1 from public.classes where id=requested_class_id and status='active'
    and (owner_user_id=auth.uid() or public.is_platform_admin()) for update;
  if not found then raise exception 'Active Class is unavailable'; end if;
  if release_row.owner_user_id<>auth.uid() and not public.is_platform_admin() then raise exception 'Course Release is unavailable'; end if;
  select * into current_row from public.class_course_assignments
    where class_id=requested_class_id and source_course_id=release_row.course_id and status='active' for update;
  if current_row.id is not null and current_row.course_release_id=requested_release_id then
    update public.class_course_assignments set available_at=requested_available_at,due_at=requested_due_at,updated_at=pg_catalog.now() where id=current_row.id;
    return current_row.id;
  end if;
  update public.class_course_assignments set status='inactive',ended_at=pg_catalog.now(),updated_at=pg_catalog.now()
    where id=current_row.id;
  insert into public.class_course_assignments(class_id,course_release_id,source_course_id,assigned_by,available_at,due_at)
    values(requested_class_id,requested_release_id,release_row.course_id,auth.uid(),requested_available_at,requested_due_at)
    returning id into created_id;
  if current_row.id is not null then
    perform public.project_assignment_release_progress(requested_class_id,current_row.course_release_id,requested_release_id);
  else
    perform public.notify_assignment_learners(created_id);
  end if;
  return created_id;
end; $$;

create or replace function public.notify_enrollment_assignments()
returns trigger language plpgsql security definer set search_path='' as $$
declare assignment_row record;
begin
  if new.status='active' then
    for assignment_row in select id from public.class_course_assignments where class_id=new.class_id and status='active' loop
      perform public.create_assignment_notification(assignment_row.id,new.learner_user_id,'new_assignment','assignment:'||assignment_row.id||':new');
    end loop;
  end if;
  return new;
end; $$;
create trigger class_enrollment_assignment_notifications after insert or update of status on public.class_enrollments for each row execute function public.notify_enrollment_assignments();

create or replace function public.process_assignment_notifications_at(requested_now timestamptz)
returns integer language plpgsql security definer set search_path='' as $$
declare assignment_row record; enrollment_row record; total_lessons integer; completed_lessons integer; generated integer:=0; notification_id bigint;
begin
  for assignment_row in select * from public.class_course_assignments where status='active' loop
    for enrollment_row in select learner_user_id from public.class_enrollments where class_id=assignment_row.class_id and status='active' loop
      if assignment_row.available_at is not null and assignment_row.available_at <= requested_now then
        select public.create_assignment_notification(assignment_row.id,enrollment_row.learner_user_id,'assignment_available','assignment:'||assignment_row.id||':available:'||to_char(assignment_row.available_at,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) into notification_id;
        generated:=generated+case when notification_id is null then 0 else 1 end;
      end if;
      select count(*) into total_lessons from public.course_release_lessons l join public.course_release_units u on u.id=l.course_release_unit_id where u.course_release_id=assignment_row.course_release_id;
      select count(*) into completed_lessons from public.learner_release_lesson_progress p join public.course_release_lessons l on l.id=p.course_release_lesson_id join public.course_release_units u on u.id=l.course_release_unit_id where p.learner_id=enrollment_row.learner_user_id and u.course_release_id=assignment_row.course_release_id and p.completed_at is not null;
      if total_lessons=0 or completed_lessons < total_lessons then
        if assignment_row.due_at is not null and assignment_row.due_at > requested_now and assignment_row.due_at <= requested_now + interval '24 hours' then
          select public.create_assignment_notification(assignment_row.id,enrollment_row.learner_user_id,'due_soon','assignment:'||assignment_row.id||':due_soon:'||to_char(assignment_row.due_at,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) into notification_id;
          generated:=generated+case when notification_id is null then 0 else 1 end;
        elsif assignment_row.due_at is not null and assignment_row.due_at < requested_now then
          select public.create_assignment_notification(assignment_row.id,enrollment_row.learner_user_id,'assignment_late','assignment:'||assignment_row.id||':late:'||to_char(assignment_row.due_at,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) into notification_id;
          generated:=generated+case when notification_id is null then 0 else 1 end;
        end if;
      end if;
    end loop;
  end loop;
  return generated;
end; $$;
create or replace function public.process_assignment_notifications() returns integer language sql security definer set search_path='' as $$ select public.process_assignment_notifications_at(pg_catalog.now()); $$;

create or replace function public.get_my_notifications(requested_limit integer default 50)
returns jsonb language sql stable security definer set search_path='' as $$
  select coalesce(jsonb_agg(item order by item->>'createdAt' desc), '[]'::jsonb)
  from (
    select jsonb_build_object('id',n.id,'type',n.notification_type,'classId',n.class_id,'assignmentId',n.assignment_id,'releaseId',n.course_release_id,'title',n.title,'body',n.body,'metadata',n.metadata,'createdAt',n.created_at,'readAt',n.read_at) as item
    from public.learner_notifications n
    where n.learner_user_id=auth.uid()
    order by n.created_at desc
    limit least(greatest(coalesce(requested_limit,50),1),100)
  ) items;
$$;
create or replace function public.mark_notification_read(requested_notification_id bigint) returns void language sql security definer set search_path='' as $$ update public.learner_notifications set read_at=coalesce(read_at,pg_catalog.now()) where id=requested_notification_id and learner_user_id=auth.uid(); $$;
create or replace function public.mark_all_notifications_read() returns void language sql security definer set search_path='' as $$ update public.learner_notifications set read_at=coalesce(read_at,pg_catalog.now()) where learner_user_id=auth.uid() and read_at is null; $$;

-- The processor is deterministic and callable by a trusted scheduler. pg_cron is
-- local/managed Supabase infrastructure; no learner role can execute it.
create extension if not exists pg_cron with schema extensions;
select cron.schedule('pronouncelab-assignment-notifications','*/15 * * * *','select public.process_assignment_notifications()')
where not exists(select 1 from cron.job where jobname='pronouncelab-assignment-notifications');

revoke all on function public.create_assignment_notification(bigint,uuid,text,text),public.notify_assignment_learners(bigint),public.process_assignment_notifications_at(timestamptz),public.process_assignment_notifications() from public,anon,authenticated;
revoke all on function public.get_my_notifications(integer),public.mark_notification_read(bigint),public.mark_all_notifications_read() from public,anon;
grant execute on function public.get_my_notifications(integer),public.mark_notification_read(bigint),public.mark_all_notifications_read() to authenticated;

commit;
