begin;

create type public.class_status as enum ('active', 'archived');
create type public.class_enrollment_status as enum ('active', 'inactive');

create table public.classes (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  description text not null default '' check (char_length(description) <= 1000),
  status public.class_status not null default 'active',
  join_code text not null unique check (join_code ~ '^[A-F0-9]{16}$'),
  join_code_enabled boolean not null default true,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now()
);

create table public.class_enrollments (
  class_id bigint not null references public.classes(id) on delete restrict,
  learner_user_id uuid not null references auth.users(id) on delete restrict,
  status public.class_enrollment_status not null default 'active',
  joined_at timestamptz not null default pg_catalog.now(),
  ended_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  primary key (class_id, learner_user_id),
  check ((status = 'active' and ended_at is null) or status = 'inactive')
);

create index classes_owner_idx on public.classes(owner_user_id, status);
create index class_enrollments_learner_idx on public.class_enrollments(learner_user_id, status);
alter table public.classes enable row level security;
alter table public.class_enrollments enable row level security;
grant select on public.classes, public.class_enrollments to authenticated;

create or replace function public.owns_class(requested_class_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.classes where id=requested_class_id and owner_user_id=auth.uid()) or public.is_platform_admin();
$$;
create or replace function public.has_active_class_enrollment(requested_class_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.class_enrollments where class_id=requested_class_id and learner_user_id=auth.uid() and status='active');
$$;

create policy classes_select_authorized on public.classes for select to authenticated
using (public.owns_class(id) or public.has_active_class_enrollment(id));
create policy enrollments_select_authorized on public.class_enrollments for select to authenticated
using (learner_user_id = auth.uid() or public.owns_class(class_id));

create or replace function public.generate_class_join_code()
returns text language sql volatile security definer set search_path = '' as $$
  select upper(encode(extensions.gen_random_bytes(8), 'hex'));
$$;

create or replace function public.create_class(requested_name text, requested_description text default '')
returns bigint language plpgsql security definer set search_path = '' as $$
declare created_id bigint; code text;
begin
  if not (public.is_content_teacher() or public.is_platform_admin()) then raise exception 'Teacher access is required'; end if;
  if btrim(coalesce(requested_name,'')) = '' then raise exception 'Class name is required'; end if;
  loop
    code := public.generate_class_join_code();
    begin
      insert into public.classes(owner_user_id,name,description,join_code)
      values(auth.uid(),btrim(requested_name),btrim(coalesce(requested_description,'')),code) returning id into created_id;
      exit;
    exception when unique_violation then null;
    end;
  end loop;
  return created_id;
end; $$;

create or replace function public.update_owned_class(requested_class_id bigint, requested_name text, requested_description text, requested_status public.class_status)
returns void language plpgsql security definer set search_path = '' as $$
begin
  update public.classes set name=btrim(requested_name), description=btrim(coalesce(requested_description,'')), status=requested_status,
    join_code_enabled=case when requested_status='archived' then false else join_code_enabled end, updated_at=pg_catalog.now()
  where id=requested_class_id and (owner_user_id=auth.uid() or public.is_platform_admin());
  if not found then raise exception 'Class is unavailable'; end if;
end; $$;

create or replace function public.regenerate_class_join_code(requested_class_id bigint)
returns text language plpgsql security definer set search_path = '' as $$
declare code text;
begin
  if not exists(select 1 from public.classes where id=requested_class_id and status='active' and (owner_user_id=auth.uid() or public.is_platform_admin())) then raise exception 'Active class is unavailable'; end if;
  loop
    code:=public.generate_class_join_code();
    begin update public.classes set join_code=code,join_code_enabled=true,updated_at=pg_catalog.now() where id=requested_class_id; exit;
    exception when unique_violation then null; end;
  end loop;
  return code;
end; $$;

create or replace function public.join_class(requested_join_code text)
returns bigint language plpgsql security definer set search_path = '' as $$
declare target bigint;
begin
  if not public.is_learner_identity() then raise exception 'Learner authentication is required'; end if;
  select id into target from public.classes where join_code=upper(btrim(requested_join_code)) and join_code_enabled and status='active';
  if target is null then raise exception 'Join code is invalid or unavailable'; end if;
  insert into public.class_enrollments(class_id,learner_user_id) values(target,auth.uid())
  on conflict(class_id,learner_user_id) do update set status='active',ended_at=null,joined_at=pg_catalog.now(),updated_at=pg_catalog.now();
  return target;
end; $$;

create or replace function public.set_class_enrollment_active(requested_class_id bigint, requested_learner_id uuid, requested_active boolean)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not exists(select 1 from public.classes where id=requested_class_id and (owner_user_id=auth.uid() or public.is_platform_admin())) then raise exception 'Class is unavailable'; end if;
  update public.class_enrollments set status=case when requested_active then 'active'::public.class_enrollment_status else 'inactive'::public.class_enrollment_status end,
    ended_at=case when requested_active then null else pg_catalog.now() end, joined_at=case when requested_active then pg_catalog.now() else joined_at end, updated_at=pg_catalog.now()
  where class_id=requested_class_id and learner_user_id=requested_learner_id;
  if not found then raise exception 'Enrollment is unavailable'; end if;
end; $$;

create or replace function public.get_owned_class_roster(requested_class_id bigint)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not exists(select 1 from public.classes where id=requested_class_id and (owner_user_id=auth.uid() or public.is_platform_admin())) then raise exception 'Class is unavailable'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object('learnerId',e.learner_user_id,'email',u.email,'status',e.status,'joinedAt',e.joined_at) order by u.email)
    from public.class_enrollments e join auth.users u on u.id=e.learner_user_id where e.class_id=requested_class_id),'[]'::jsonb);
end; $$;

create or replace function public.get_enrolled_learner_progress_summary(requested_class_id bigint)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not exists(select 1 from public.classes where id=requested_class_id and (owner_user_id=auth.uid() or public.is_platform_admin())) then raise exception 'Class is unavailable'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object('learnerId',e.learner_user_id,'email',u.email,
    'startedLessons',(select count(*) from public.learner_lesson_progress p where p.learner_id=e.learner_user_id),
    'completedLessons',(select count(*) from public.learner_lesson_progress p where p.learner_id=e.learner_user_id and p.completed_at is not null),
    'lastAccessedAt',(select max(p.last_accessed_at) from public.learner_lesson_progress p where p.learner_id=e.learner_user_id)) order by u.email)
    from public.class_enrollments e join auth.users u on u.id=e.learner_user_id where e.class_id=requested_class_id and e.status='active'),'[]'::jsonb);
end; $$;

revoke all on table public.classes, public.class_enrollments from anon;
revoke all on function public.generate_class_join_code() from public,anon,authenticated;
revoke all on function public.owns_class(bigint), public.has_active_class_enrollment(bigint) from public,anon,authenticated;
grant execute on function public.owns_class(bigint), public.has_active_class_enrollment(bigint) to authenticated;
revoke all on function public.create_class(text,text), public.update_owned_class(bigint,text,text,public.class_status), public.regenerate_class_join_code(bigint), public.join_class(text), public.set_class_enrollment_active(bigint,uuid,boolean), public.get_owned_class_roster(bigint), public.get_enrolled_learner_progress_summary(bigint) from public,anon;
grant execute on function public.create_class(text,text), public.update_owned_class(bigint,text,text,public.class_status), public.regenerate_class_join_code(bigint), public.join_class(text), public.set_class_enrollment_active(bigint,uuid,boolean), public.get_owned_class_roster(bigint), public.get_enrolled_learner_progress_summary(bigint) to authenticated;

commit;
