begin;

alter type public.lesson_activity_type
  add value if not exists 'ai_speaking_mission';

-- PostgreSQL requires a newly added enum value to be committed before it can
-- be referenced by table constraints, policies, or PL/pgSQL function bodies.
commit;
begin;

create table public.ai_speaking_missions (
  id bigint generated by default as identity primary key,
  activity_id bigint not null unique
    references public.lesson_activities (id) on delete cascade,
  config jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_speaking_missions_config_object
    check (jsonb_typeof(config) = 'object'),
  constraint ai_speaking_missions_config_size
    check (octet_length(config::text) <= 50000),
  constraint ai_speaking_missions_required_shape
    check (
      config ?& array[
        'missionTitle', 'cefrLevel', 'goal',
        'primarySoundLabel', 'primarySoundIpa',
        'primaryWords', 'sentences', 'readingText',
        'supportedTools', 'resultFormatVersion'
      ]
      and jsonb_typeof(config -> 'primaryWords') = 'array'
      and jsonb_typeof(config -> 'secondaryWords') = 'array'
      and jsonb_typeof(config -> 'sentences') = 'array'
      and jsonb_typeof(config -> 'supportedTools') = 'array'
    ),
  constraint ai_speaking_missions_format_version
    check (
      jsonb_typeof(config -> 'resultFormatVersion') = 'number'
      and (config ->> 'resultFormatVersion')::integer = 1
    )
);

alter table public.ai_speaking_missions enable row level security;

grant select on public.ai_speaking_missions to anon, authenticated;
grant insert, update, delete on public.ai_speaking_missions to authenticated;
grant usage, select on sequence public.ai_speaking_missions_id_seq to authenticated;

create policy "ai_speaking_missions_select_published_or_manager"
on public.ai_speaking_missions for select
to anon, authenticated
using (
  public.is_published_activity(activity_id)
  or public.can_manage_content()
);

create policy "ai_speaking_missions_insert_draft"
on public.ai_speaking_missions for insert
to authenticated
with check (
  public.can_edit_drafts()
  and public.is_draft_activity(activity_id)
);

create policy "ai_speaking_missions_update_draft"
on public.ai_speaking_missions for update
to authenticated
using (
  public.can_edit_drafts()
  and public.is_draft_activity(activity_id)
)
with check (
  public.can_edit_drafts()
  and public.is_draft_activity(activity_id)
);

create policy "ai_speaking_missions_delete_draft"
on public.ai_speaking_missions for delete
to authenticated
using (
  public.can_edit_drafts()
  and public.is_draft_activity(activity_id)
);

create trigger ai_speaking_missions_set_updated_at
before update on public.ai_speaking_missions
for each row execute function public.set_updated_at();

create or replace function public.protect_ai_speaking_mission()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  parent_activity_id bigint;
begin
  perform public.lock_content_hierarchy_gate();

  if tg_op = 'UPDATE'
    and new.activity_id is distinct from old.activity_id
  then
    raise exception 'AI speaking mission parent is immutable';
  end if;

  parent_activity_id := case
    when tg_op = 'DELETE' then old.activity_id
    else new.activity_id
  end;

  perform 1
  from public.lesson_activities as activity
  join public.lesson_versions as version
    on version.id = activity.lesson_version_id
  join public.lessons as lesson
    on lesson.id = version.lesson_id
  join public.units as unit on unit.id = lesson.unit_id
  join public.courses as course on course.id = unit.course_id
  where activity.id = parent_activity_id
    and activity.type = 'ai_speaking_mission'
    and version.status = 'draft'
    and lesson.status = 'draft'
    and unit.status = 'draft'
    and course.status = 'draft'
  for update of activity, version, lesson, unit, course;

  if not found then
    raise exception 'The expected draft AI speaking mission is unavailable';
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function public.protect_ai_speaking_mission() from public;

create trigger ai_speaking_missions_protect_version
before insert or update or delete on public.ai_speaking_missions
for each row execute function public.protect_ai_speaking_mission();

create or replace function public.create_draft_ai_speaking_mission(
  requested_lesson_version_id bigint,
  requested_title text,
  requested_config jsonb
)
returns public.lesson_activities
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.lesson_activities;
  next_position integer;
  clean_title text := btrim(requested_title);
begin
  perform public.lock_content_hierarchy_gate();

  if not public.can_edit_drafts() then
    raise exception 'Draft editing permission is required';
  end if;
  if clean_title is null or clean_title = '' then
    raise exception 'Activity title is required';
  end if;
  if jsonb_typeof(requested_config) <> 'object'
    or not (requested_config ? 'resultFormatVersion')
    or (requested_config ->> 'resultFormatVersion')::integer <> 1
  then
    raise exception 'A valid Format Version 1 mission configuration is required';
  end if;

  perform 1
  from public.lesson_versions as version
  join public.lessons as lesson on lesson.id = version.lesson_id
  join public.units as unit on unit.id = lesson.unit_id
  join public.courses as course on course.id = unit.course_id
  where version.id = requested_lesson_version_id
    and version.status = 'draft'
    and lesson.status = 'draft'
    and unit.status = 'draft'
    and course.status = 'draft'
  for update of version, lesson, unit, course;
  if not found then
    raise exception 'The expected draft lesson version is unavailable';
  end if;

  perform 1 from public.lesson_activities as activity
  where activity.lesson_version_id = requested_lesson_version_id
  order by activity.id for update;

  select coalesce(max(activity.position), -1) + 1 into next_position
  from public.lesson_activities as activity
  where activity.lesson_version_id = requested_lesson_version_id;

  insert into public.lesson_activities (
    lesson_version_id, type, title, position, required
  ) values (
    requested_lesson_version_id, 'ai_speaking_mission',
    clean_title, next_position, true
  ) returning * into result;

  insert into public.ai_speaking_missions (activity_id, config)
  values (result.id, requested_config);

  return result;
end;
$$;

revoke all on function public.create_draft_ai_speaking_mission(
  bigint, text, jsonb
) from public, anon;
grant execute on function public.create_draft_ai_speaking_mission(
  bigint, text, jsonb
) to authenticated;

create or replace function public.duplicate_draft_ai_speaking_mission(
  requested_activity_id bigint,
  expected_lesson_version_id bigint
)
returns public.lesson_activities
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_activity public.lesson_activities;
  source_config jsonb;
  result public.lesson_activities;
  next_position integer;
begin
  perform public.lock_content_hierarchy_gate();
  if not public.can_edit_drafts() then
    raise exception 'Draft editing permission is required';
  end if;

  select activity.*
  into source_activity
  from public.lesson_activities as activity
  join public.ai_speaking_missions as mission
    on mission.activity_id = activity.id
  join public.lesson_versions as version
    on version.id = activity.lesson_version_id
  join public.lessons as lesson on lesson.id = version.lesson_id
  join public.units as unit on unit.id = lesson.unit_id
  join public.courses as course on course.id = unit.course_id
  where activity.id = requested_activity_id
    and activity.lesson_version_id = expected_lesson_version_id
    and activity.type = 'ai_speaking_mission'
    and version.status = 'draft'
    and lesson.status = 'draft'
    and unit.status = 'draft'
    and course.status = 'draft'
  for update of activity, mission, version, lesson, unit, course;
  if not found then
    raise exception 'The expected draft AI speaking mission is unavailable';
  end if;

  select mission.config into source_config
  from public.ai_speaking_missions as mission
  where mission.activity_id = requested_activity_id
  for update;

  perform 1 from public.lesson_activities as activity
  where activity.lesson_version_id = expected_lesson_version_id
  order by activity.id for update;

  select coalesce(max(activity.position), -1) + 1 into next_position
  from public.lesson_activities as activity
  where activity.lesson_version_id = expected_lesson_version_id;

  insert into public.lesson_activities (
    lesson_version_id, type, title, position, required
  ) values (
    expected_lesson_version_id, 'ai_speaking_mission',
    source_activity.title || ' copy', next_position,
    source_activity.required
  ) returning * into result;

  insert into public.ai_speaking_missions (activity_id, config)
  values (result.id, source_config);
  return result;
end;
$$;

revoke all on function public.duplicate_draft_ai_speaking_mission(
  bigint, bigint
) from public, anon;
grant execute on function public.duplicate_draft_ai_speaking_mission(
  bigint, bigint
) to authenticated;

commit;
